Models/AuthorModel.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Library.Models;

public class AuthorModel
{
    [BsonId]
    public ObjectId Id { get; set; }
    
    [BsonElement("name")]
    public string Name { get; set; }
    
    [BsonElement("paternalSurname")]
    public string PaternalSurname { get; set; }
    
    [BsonElement("maternalSurname")]
    public string MaternalSurname { get; set; }
    
    [BsonElement("phone")]
    public string Phone { get; set; }
    
    [BsonElement("address")]
    public string Address { get; set; }
}

Models/BookModel.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Library.Models;

public class BookModel
{
    [BsonId]
    public ObjectId Id { get; set; }
    
    [BsonElement("isbn")]
    public string ISBN { get; set; }
    
    [BsonElement("title")]
    public string Title { get; set; }
    
    [BsonElement("author")]
    public ObjectId Author { get; set; }
    
    [BsonElement("editorial")]
    public string Editorial { get; set; }
    
    [BsonElement("publishDate")]
    public int PublishDate { get; set; }
}

Models/ErrorViewModel.cs
namespace Library.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AuthorController.cs
using Library.Collections;
using Library.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers;

public class AuthorController : Controller
{
    private readonly ILogger<AuthorController> _logger;
    private readonly AuthorCollection _collection;
    
    public AuthorController(ILogger<AuthorController> logger)
    {
        _logger = logger;
        _collection = new AuthorCollection();
    }
    
    // GET
    public IActionResult Index(string id)
    {
        var authors = _collection.GetAuthors();
        return View(authors);
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    public IActionResult Edit(string id)
    {
        var author = _collection.GetAuthor(id);
        return View(author);
    }
    
    // HTTP METHODS
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(AuthorModel author)
    {
        if (!ModelState.IsValid) return View(author);
        _collection.InsertAuthor(author);
        return RedirectToAction(nameof(Index));
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(string id, AuthorModel author)
    {
        if (!ModelState.IsValid) return View(author);
        _collection.UpdateAuthor(id, author);
        return RedirectToAction(nameof(Index));
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(string id)
    {
        var relatedBooks = new BookCollection().GetBooksByAuthor(id);
        if (relatedBooks.Count > 0)
        {
            ViewBag.Error = "No se puede eliminar un autor que tiene libros asociados";
            return View(nameof(Index), _collection.GetAuthors());
        }
        _collection.DeleteAuthor(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/BookController.cs
using Library.Collections;
using Library.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers;

public class BookController : Controller
{
    private readonly ILogger<AuthorController> _logger;
    private readonly BookCollection _collection;
    
    public BookController(ILogger<AuthorController> logger)
    {
        _logger = logger;
        _collection = new BookCollection();
    }
    
    // GET
    public IActionResult Index()
    {
        var books = _collection.GetBooks();
        var authors = new AuthorCollection().GetAuthors();
    
        var authorMap = authors.ToDictionary(author => author.Id.ToString(), author => author.Name + " " + author.PaternalSurname + " " + author.MaternalSurname);

        ViewBag.AuthorMap = authorMap;
    
        return View(books);
    }
    
    public IActionResult Create()
    {
        var authors = new AuthorCollection().GetAuthors();
        var authorsList = authors.Select(a => new 
        { 
            Id = a.Id, 
            FullName = $"{a.Name} {a.PaternalSurname} {a.MaternalSurname}" 
        }).ToList();
        ViewBag.Authors = authorsList;
        
        int currentYear = DateTime.Now.Year;
        List<int> years = Enumerable.Range(1900, currentYear - 1900 + 1).ToList();
        ViewBag.Years = years;
        
        return View();
    }
    
    public IActionResult Edit(string id)
    {
        var authors = new AuthorCollection().GetAuthors();
        var authorsList = authors.Select(a => new 
        { 
            Id = a.Id, 
            FullName = $"{a.Name} {a.PaternalSurname} {a.MaternalSurname}" 
        }).ToList();
        ViewBag.Authors = authorsList;
        var book = _collection.GetBook(id);
        
        int currentYear = DateTime.Now.Year;
        List<int> years = Enumerable.Range(1900, currentYear - 1900 + 1).ToList();
        ViewBag.Years = years;
        
        return View(book);
    }
    
    // HTTP METHODS
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(BookModel book)
    {
        if (!ModelState.IsValid) return View(book);
        _collection.InsertBook(book);
        return RedirectToAction(nameof(Index));
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(string id, BookModel book)
    {
        if (!ModelState.IsValid) return View(book);
        _collection.UpdateBook(id, book);
        return RedirectToAction(nameof(Index));
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(string id)
    {
        _collection.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Library.Models;

namespace Library.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Author/Create.cshtml
@model Library.Models.AuthorModel

@{
    ViewData["Title"] = "Create";
}

<h1>@ViewData["Title"]</h1>
<h4>Author</h4>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Create">
                <div class="mb-3">
                    <label asp-for="Name">Nombre</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PaternalSurname">Apellido Paterno</label>
                    <input asp-for="PaternalSurname" class="form-control" />
                    <span asp-validation-for="PaternalSurname" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="MaternalSurname">Apellido Materno</label>
                    <input asp-for="MaternalSurname" class="form-control" />
                    <span asp-validation-for="MaternalSurname" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Phone">Teléfono</label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Address">Dirección</label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <input type="submit" value="Create" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Author/Edit.cshtml
@model Library.Models.AuthorModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData["Title"]</h1>
<h4>Student</h4>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Edit" method="post">
                <div class="mb-3">
                    <label asp-for="Name">Nombre</label>
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PaternalSurname">Apellido Paterno</label>
                    <input asp-for="PaternalSurname" class="form-control"/>
                    <span asp-validation-for="PaternalSurname" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="MaternalSurname">Apellido Materno</label>
                    <input asp-for="MaternalSurname" class="form-control"/>
                    <span asp-validation-for="MaternalSurname" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Phone">Teléfono</label>
                    <input asp-for="Phone" class="form-control"/>
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Address">Dirección</label>
                    <input asp-for="Address" class="form-control"/>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Author/Index.cshtml
@{
    ViewData["Title"] = "Authors";
}

<h1>@ViewData["Title"]</h1>

@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div class="alert alert-danger">
        @ViewBag.Error
    </div>
}

<div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Teléfono</th>
            <th>Dirección</th>
            <th colspan="1">Acciones</th>
        </tr>
        </thead>

        <tbody>
        @foreach (var author in Model)
        {
            <tr>
                <td>@author.Name</td>
                <td>@author.PaternalSurname</td>
                <td>@author.MaternalSurname</td>
                <td>@author.Phone</td>
                <td>@author.Address</td>
                <td>
                    <a asp-action="Edit" asp-controller="Author" asp-route-id="@author.Id" class="btn btn-outline-primary">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                    <form asp-action="Delete" asp-controller="Author" asp-route-id="@author.Id" method="post" class="d-inline">
                        <input type="hidden" name="__RequestVerificationToken" value="@Html.AntiForgeryToken()" />
                        <button type="submit" class="btn btn-outline-danger" onclick="return confirm('¿Está seguro que desea eliminar este registro?');">
                            <i class="fa fa-trash"></i> Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

Views/Book/Create.cshtml
@model Library.Models.BookModel

@{
    ViewData["Title"] = "Create";
}

<h1>@ViewData["Title"]</h1>
<h4>Book</h4>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Create">
                <div class="mb-3">
                    <label asp-for="ISBN">ISBN</label>
                    <input asp-for="ISBN" class="form-control"/>
                    <span asp-validation-for="ISBN" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Title">Título</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Author">Autor</label>
                    <select asp-for="Author" class="form-control" asp-items="@(new SelectList(ViewBag.Authors, "Id", "FullName"))">
                        <option value="">Seleccione un autor</option>
                    </select>
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Editorial">Editorial</label>
                    <input asp-for="Editorial" class="form-control" />
                    <span asp-validation-for="Editorial" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="PublishDate">Año de Publicación</label>
                    <select asp-for="PublishDate" class="form-control" asp-items="@(new SelectList(ViewBag.Years))">
                        <option value="">Seleccione un año</option>
                    </select>
                    <span asp-validation-for="PublishDate" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <input type="submit" value="Create" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Book/Edit.cshtml
@model Library.Models.BookModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData["Title"]</h1>
<h4>Book</h4>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <form asp-action="Edit" method="post">
                <div class="mb-3">
                    <label asp-for="ISBN">ISBN</label>
                    <input asp-for="ISBN" class="form-control" readonly/>
                    <span asp-validation-for="ISBN" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Title">Título</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Author">Autor</label>
                    <select asp-for="Author" class="form-control" asp-items="@(new SelectList(ViewBag.Authors, "Id", "FullName"))">
                        <option value="">Seleccione un autor</option>
                    </select>
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Editorial">Editorial</label>
                    <input asp-for="Editorial" class="form-control" />
                    <span asp-validation-for="Editorial" class="text-danger"></span>
                </div>
                <!--
                <div class="mb-3">
                    <label asp-for="PublishDate">Fecha de Publicación</label>
                    <input asp-for="PublishDate" class="form-control" />
                    <span asp-validation-for="PublishDate" class="text-danger"></span>
                </div>
                --->
                <div class="mb-3">
                    <label asp-for="PublishDate">Año de Publicación</label>
                    <select asp-for="PublishDate" class="form-control" asp-items="@(new SelectList(ViewBag.Years))">
                        <option value="">Seleccione un año</option>
                    </select>
                    <span asp-validation-for="PublishDate" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Book/Index.cshtml
@{
    ViewData["Title"] = "Books";
    var authorMap = (Dictionary<string, string>)ViewBag.AuthorMap;
}

<h1>@ViewData["Title"]</h1>

<div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>ISBN</th>
            <th>Título</th>
            <th>Autor</th>
            <th>Editorial</th>
            <th>Año de Publicación</th>
            <th colspan="1">Acciones</th>
        </tr>
        </thead>

        <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.ISBN</td>
                <td>@book.Title</td>
                <td>@authorMap[book.Author.ToString()]</td>
                <td>@book.Editorial</td>
                <td>@book.PublishDate</td>
                <td>
                    <a asp-action="Edit" asp-controller="Book" asp-route-id="@book.Id" class="btn btn-outline-primary">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                    <form asp-action="Delete" asp-controller="Book" asp-route-id="@book.Id" method="post" class="d-inline">
                        <input type="hidden" name="__RequestVerificationToken" value="@Html.AntiForgeryToken()" />
                        <button type="submit" class="btn btn-outline-danger" onclick="return confirm('¿Está seguro que desea eliminar este registro?');">
                            <i class="fa fa-trash"></i> Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Authors
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Author" asp-action="Index">All Authors</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Author" asp-action="Create">Add Author</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Books
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Book" asp-action="Index">All Books</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Book" asp-action="Create">Add Book</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>